service: triplecheck-example-lambda

frameworkVersion: ">=2.4.0"

provider:
  name: aws
  runtime: nodejs14.x
  stage: ${opt:stage, 'dev'}
  region: ${self:custom.region}
  memorySize: 2048
  timeout: 20
  logRetentionInDays: 14
  deploymentBucket:
    blockPublicAccess: true
    maxPreviousDeploymentArtifacts: 5
    serverSideEncryption: AES256
  stackTags:
    Usage: ${self:service}
  tags:
    Usage: ${self:service}
  versionFunctions: false
  iamRoleStatements:
  - Effect: Allow
    Action:
      - dynamodb:GetItem
      - dynamodb:PutItem
      - dynamodb:DeleteItem
    Resource:
      -  arn:aws:dynamodb:${self:custom.region}:${self:custom.awsAccountNumber}:table/${self:custom.dynamoTableName}

# EDIT THESE TO YOUR VALUES!
custom:
  awsAccountNumber: 123412341234
  region: eu-north-1
  dynamoTableName: broker-database

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  triplecheck:
    handler: src/index.handler
    description: TripleCheck broker
    events:
      - http:
          method: GET
          path: /{any+}
      - http:
          method: PUT
          path: /{any+}
      - http:
          method: POST
          path: /{any+}
      - http:
          method: DELETE
          path: /{any+}
      - http:
          method: OPTIONS
          path: /{any+}

resources:
  Resources:
    BrokerDatabase:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.dynamoTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST